### ISSUE TITLE
Add Jaeger logo

### ISSUE THREAD

**Issue by jpkrohling** [openshift/openshift-logos-icon#21]
Right now, the Jaeger template for OpenShift is using Go's gopher. Ideally, we'd like to use Jaeger's own logo: https://github.com/jaegertracing/artwork

Ref: https://github.com/jaegertracing/jaeger-openshift/pull/92

**Comment by jpkrohling** [comment]
@rhamilto, would this be something that would get merged if I send a PR? If so, are there instructions somewhere on how to do it?

**Comment by rhamilto** [comment]
@jpkrohling.  PRs welcome!  See https://github.com/openshift/openshift-logos-icon#contributing

**Comment by jpkrohling** [comment]
Created #22

**Comment by jpkrohling** [comment]
That was quick, thanks! When will be the next release? Once this is available in OpenShift, I'll update our templates to make use of this new icon.

**Comment by rhamilto** [comment]
The next release will be 4.0.  I've [opened a PR to make use of the v1.7.0 release including the Jaeger icon](https://github.com/openshift/console/pull/575) in the new console.  

In addition to the icon, the console also has an optional color image replacement of the icon.  See https://github.com/openshift/console/blob/master/frontend/public/components/catalog-item-icon.tsx#L7-L176.  If you have a color image, you can either open a PR to console or you can supply me with the image and I'll take care of it for you.  Usage wise, nothing changes.  You'll still update the templates to include `icon-jaeger`, but instead of the monochrome font icon, you'll get the color image.  :)

**Comment by jpkrohling** [comment]
That's nice! At this moment, we have only the EPS version here:
https://github.com/jaegertracing/artwork/blob/master/EPS/Jaeger_Logo_Final_PANTONE.eps

And the PNG:
https://github.com/jaegertracing/artwork/blob/master/PNG/Jaeger_Logo_Final_PANTONE.png

A PR is on its way, providing a SVG:
https://github.com/jaegertracing/artwork/pull/4
https://github.com/jaegertracing/artwork/blob/16507f99bf1199994852e19b2600d0b726bb2d3b/SVG/Jaeger_Logo_Final_PANTONE.svg

**Comment by rhamilto** [comment]
> https://github.com/jaegertracing/artwork/blob/16507f99bf1199994852e19b2600d0b726bb2d3b/SVG/Jaeger_Logo_Final_PANTONE.svg

I recommend trimming the extra canvas surrounding the image in the SVG to maximize the size of the image on the page.  For example, https://github.com/openshift/console/blob/master/frontend/public/imgs/logos/3scale.svg

**Comment by jpkrohling** [comment]
Something like this? https://github.com/jaegertracing/artwork/blob/b8d9b68b98e5652718af77be880052744cdd1ee6/SVG/Jaeger_Logo_Final_PANTONE.svg

**Comment by rhamilto** [comment]
Perfect!
